# Generated by Django 3.1.4 on 2021-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
