# Generated by Django 3.1.4 on 2021-08-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210821_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
