# Generated by Django 3.1.4 on 2021-08-27 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20210827_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='New_Arrival',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 15, 14, 31, 841745)),
        ),
    ]
